name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-apply.yml'
  workflow_dispatch:
    inputs:
      confirm:
        description: '확인을 위해 destroy 입력'
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  TF_WORKING_DIR: ./terraform
  TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production      # ← 승인 게이트
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}